export interface MoreUser{
    id : number;
    firstName: string;
    middleName: string;
    lastName: string;
    dob: String;
    maritalStatus: string;
    ssn: String;
    loanAmount: number;
    loanPurpose: string;
    description: String;
    addressLine1: string;
    addressLine2: string;
    city: string;
    state: string;
    postalCode: string;
    homePhone: string;
    officePhone: string;
    mobileNumber: string;
    email: string;
    employerName: string;
    annualSalary: number;
    experienceYears: number;
    experienceMonths: number;
    designation: string;
    employerAddressLine1: string;
    employerAddressLine2: string;
    employerCity: string;
    employerState: string;
    employerPostalCode: string;
    status: string;
    score: number;
    reason: string;
    date : string;
}